<a href="https://colab.research.google.com/github/amansin05/Movie-Recommender-System/blob/main/Movie_Recommender_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [87]:
import numpy as np
import pandas as pd

In [88]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [89]:
movies = pd.read_csv('/content/tmdb_5000_movies.csv',engine='python', error_bad_lines=False)
credits = pd.read_csv('/content/tmdb_5000_credits.csv',engine='python', error_bad_lines=False)

<ipython-input-89-3fbb6295d863>:1: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  movies = pd.read_csv('/content/tmdb_5000_movies.csv',engine='python', error_bad_lines=False)
Skipping line 1573: unexpected end of data
<ipython-input-89-3fbb6295d863>:2: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  credits = pd.read_csv('/content/tmdb_5000_credits.csv',engine='python', error_bad_lines=False)

In [90]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [91]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [92]:
movies = movies.merge(credits,on='title')

In [93]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [94]:
# genres
# id
# keywords
# title
# overview
# cast
# crew

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [95]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [96]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [97]:
movies.dropna(inplace=True)

In [98]:
movies.duplicated().sum()

0

In [99]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [100]:
# '[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [101]:
def convert(obj):
  L= []
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L

In [102]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [103]:
 movies['genres'] = movies['genres'].apply(convert)

In [104]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [105]:
movies['keywords'] = movies['keywords'].apply(convert)

In [106]:
 movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [107]:
def convert3(obj):
  L=[]
  counter=0
  for i in ast.literal_eval(obj):
    if counter!=3:
      L.append(i['name'])
      counter+=1
    else:
        break
  return L

In [108]:
movies['cast'] = movies['cast'].apply(convert3)

In [109]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [110]:
def fetch_director(obj):
  L= []
  for i in ast.literal_eval(obj):
      if i['job'] == 'Director':
          L.append(i['name'])
          break

  return L

In [111]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [112]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [113]:
# converting overview string to lists
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [114]:
# Till now we have done preprocessing of the data and whole data is converted to lists
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [115]:
# here we have to remove spaces between names so that if we create tags names dosen't point to different words
#Sam Worthington
#SamWorthington
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","")for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","")for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","")for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","")for i in x])

In [116]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [117]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [118]:
movies['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [119]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [120]:
new_df = movies[['movie_id','title','tags']]
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
1568,2755,About Schmidt,"[66-year-old, Warren, Schmidt, is, a, retired,..."
1569,82654,Warm Bodies,"[After, a, zombie, becomes, involved, with, th..."
1570,59967,Looper,"[In, the, futuristic, action, thriller, Looper..."
1571,16300,Down to Earth,"[After, dying, before, his, time,, an, aspirin..."
1572,9598,Babe,"[Babe, is, a, little, pig, who, doesn't, quite..."

In [121]:
# converting lists to string in tags
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

<ipython-input-121-e9821a25b3b5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [122]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [123]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [124]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

<ipython-input-124-8b60b591a07f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [125]:
 from sklearn.feature_extraction.text import CountVectorizer
 cv = CountVectorizer(max_features=5000,stop_words='english')

In [126]:
vectors = cv.fit_transform(new_df['tags']).toarray()
#in this most of the values will be zero,by default countvectorizer results a matrix which we convert it to an numpy array

In [127]:
vectors[0]
#in this not every value is zero the movie containing the words will have 1

array([0, 0, 0, ..., 0, 0, 0])

In [128]:
#most common words in the combined tag
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zoo', 'zooeydeschanel', 'zookeeper'],
      dtype=object)

In [129]:
# stemming is used to similarize the similar kinds of words
#['loved','love','loving'] changes to
#['love','love','love']

In [130]:
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [131]:
def stem(text):
    y=[]

    for i in text.split():  #converting string to lists then stemming it
        y.append(ps.stem(i))

    return " ".join(y)  #again converting it to string

In [132]:
stem('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron')

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

In [133]:
new_df['tags'] = new_df['tags'].apply(stem)

<ipython-input-133-be18a4346d89>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [134]:
from sklearn.metrics.pairwise import cosine_similarity

In [135]:
 cosine_similarity(vectors).shape  # it tells the similarity btw ecah mocie with every other movie here we have 4806 movies

(1573, 1573)

In [136]:
similarity = cosine_similarity(vectors)
similarity

array([[1.        , 0.08257228, 0.05504819, ..., 0.1118034 , 0.12247449,
        0.01917412],
       [0.08257228, 1.        , 0.06060606, ..., 0.06154575, 0.08989331,
        0.04222003],
       [0.05504819, 0.06060606, 1.        , ..., 0.06154575, 0.        ,
        0.        ],
       ...,
       [0.1118034 , 0.06154575, 0.06154575, ..., 1.        , 0.09128709,
        0.04287465],
       [0.12247449, 0.08989331, 0.        , ..., 0.09128709, 1.        ,
        0.09393364],
       [0.01917412, 0.04222003, 0.        , ..., 0.04287465, 0.09393364,
        1.        ]])

In [137]:
similarity[0] # it tells us the distance of first movie with every other movie

array([1.        , 0.08257228, 0.05504819, ..., 0.1118034 , 0.12247449,
       0.01917412])

In [138]:
new_df[new_df['title'] == 'Batman Begins'].index[0]

119

In [139]:
sorted(similarity[0],reverse=True) #printing similarity in descending order but here we lose the index position therefore we use enumerate function

[1.0000000000000002,
 0.24404676504598818,
 0.23596995186213465,
 0.2345207879911715,
 0.2271099895830676,
 0.22499999999999998,
 0.22360679774997896,
 0.22140372138502384,
 0.20981358185407062,
 0.20328927815368153,
 0.20080483222562476,
 0.2,
 0.1978141420187361,
 0.1956559480312316,
 0.19364916731037088,
 0.19364916731037088,
 0.18981415059132414,
 0.18973665961010278,
 0.18446619684315546,
 0.18446619684315546,
 0.18257418583505539,
 0.1813690625275029,
 0.1813690625275029,
 0.17787811838447135,
 0.17616606585441105,
 0.17616606585441105,
 0.17616606585441105,
 0.17256712249065836,
 0.16878498775964426,
 0.16878498775964426,
 0.16878498775964423,
 0.16854996561581048,
 0.1651445647689541,
 0.1649915822768611,
 0.16484511834894675,
 0.16484511834894675,
 0.16269784336399212,
 0.1619552660357832,
 0.1619552660357832,
 0.1611258466588724,
 0.16064386578049977,
 0.16010281506708454,
 0.15975241260567347,
 0.158113883008419,
 0.15652475842498528,
 0.15389675281277312,
 0.15348515337873014,
 0.1533929977694741,
 0.15214515486254615,
 0.15203028496707427,
 0.15,
 0.15,
 0.1492405014489273,
 0.14815943949743846,
 0.14680505487867587,
 0.14638501094227999,
 0.14467284665112365,
 0.14301938838683886,
 0.14301938838683886,
 0.13801311186847084,
 0.13801311186847084,
 0.13801311186847084,
 0.13762047064079508,
 0.13762047064079508,
 0.13762047064079508,
 0.1355815361366601,
 0.1336306209562122,
 0.1328422328310143,
 0.1318760946791574,
 0.1318760946791574,
 0.1318760946791574,
 0.1318760946791574,
 0.13135265938214027,
 0.13043729868748774,
 0.12996881122750908,
 0.12909944487358058,
 0.12909944487358058,
 0.12824729401064427,
 0.12824729401064427,
 0.12780193008453875,
 0.12659242088545833,
 0.1264911064067352,
 0.12456821978060995,
 0.12452441171884351,
 0.12403473458920847,
 0.12346619958119871,
 0.12346619958119871,
 0.12346619958119871,
 0.1224744871391589,
 0.12198750911856666,
 0.12171612389003693,
 0.12171612389003693,
 0.12056070554260304,
 0.11952286093343936,
 0.11952286093343936,
 0.11952286093343935,
 0.11918282365569904,
 0.11918282365569904,
 0.11858541225631422,
 0.11785113019775792,
 0.11744404390294069,
 0.11744404390294069,
 0.11744404390294069,
 0.11656310103003922,
 0.11656310103003922,
 0.11531640100361064,
 0.11531640100361064,
 0.11531640100361064,
 0.11504474832710557,
 0.11410886614690963,
 0.11410886614690963,
 0.11359236684941297,
 0.11359236684941297,
 0.11359236684941297,
 0.1129384878631564,
 0.1129384878631564,
 0.1118033988749895,
 0.11180339887498948,
 0.11180339887498948,
 0.11070186069251191,
 0.11070186069251191,
 0.11070186069251191,
 0.11028219331407116,
 0.11009637651263607,
 0.11009637651263607,
 0.10963225241337866,
 0.10963225241337866,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10882143751650175,
 0.10859306069076735,
 0.10846522890932808,
 0.10846522890932808,
 0.10846522890932808,
 0.10758287072798381,
 0.10690449676496976,
 0.10690449676496976,
 0.10606601717798213,
 0.10564428184106459,
 0.10564428184106459,
 0.10540925533894598,
 0.10540925533894598,
 0.10540925533894598,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10397504898200727,
 0.10380684981717495,
 0.10380684981717495,
 0.10380684981717495,
 0.10350983390135313,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10259783520851541,
 0.10206207261596574,
 0.10206207261596574,
 0.10127393670836667,
 0.10127393670836667,
 0.10127393670836667,
 0.1011299793694863,
 0.10040241611281236,
 0.10040241611281236,
 0.1,
 0.1,
 0.09890707100936805,
 0.09890707100936805,
 0.09882117688026185,
 0.09877295966495897,
 0.09877295966495897,
 0.09759000729485333,
 0.09682458365518543,
 0.09682458365518543,
 0.09682458365518543,
 0.09644856443408242,
 0.09644856443408242,
 0.09644856443408242,
 0.09644856443408242,
 0.09644856443408242,
 0.09587062360592132,
 0.095831484749991,
 0.09534625892455924,
 0.09534625892455924,
 0.09534625892455924,
 0.09534625892455924,
 0.09534625892455924,
 0.09486832980505139,
 0.09486832980505139,
 0.09486832980505139,
 0.09486832980505139,
 0.09486832980505139,
 0.09486832980505139,
 0.09486832980505139,
 0.09486832980505139,
 0.09486832980505139,
 0.09486832980505139,
 0.09486832980505139,
 0.09439751632913289,
 0.09428090415820634,
 0.09428090415820634,
 0.09428090415820634,
 0.09428090415820634,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09325048082403138,
 0.09302605094190636,
 0.09302605094190636,
 0.09302605094190636,
 0.09302605094190636,
 0.09302605094190634,
 0.09225312080288851,
 0.09190182776172597,
 0.09128709291752769,
 0.09128709291752769,
 0.09128709291752769,
 0.09035079029052512,
 0.09035079029052512,
 0.09035079029052512,
 0.08964214570007953,
 0.08964214570007953,
 0.08964214570007953,
 0.08964214570007953,
 0.08964214570007953,
 0.08964214570007951,
 0.08944271909999159,
 0.08894600837060251,
 0.08856148855400953,
 0.08856148855400953,
 0.08808303292720551,
 0.08808303292720551,
 0.08808303292720551,
 0.08808303292720551,
 0.08808303292720551,
 0.08808303292720551,
 0.08808303292720551,
 0.08808303292720551,
 0.08808303292720551,
 0.08808303292720551,
 0.08784104611578832,
 0.08770580193070293,
 0.08770580193070293,
 0.08770580193070293,
 0.08677626681257791,
 0.08660254037844387,
 0.08660254037844387,
 0.08660254037844387,
 0.08660254037844387,
 0.08660254037844387,
 0.08606629658238704,
 0.08528028654224418,
 0.08528028654224418,
 0.08519427513705972,
 0.08519427513705972,
 0.08519427513705972,
 0.08519427513705972,
 0.08519427513705972,
 0.08519427513705972,
 0.08519427513705972,
 0.08519427513705972,
 0.08451542547285167,
 0.08451542547285167,
 0.08385254915624211,
 0.08385254915624211,
 0.08385254915624211,
 0.08385254915624211,
 0.08304547985373996,
 0.08304547985373996,
 0.08304547985373996,
 0.08257228238447706,
 0.08257228238447706,
 0.08257228238447706,
 0.08257228238447706,
 0.08257228238447706,
 0.08257228238447706,
 0.08233869695926184,
 0.08233869695926184,
 0.08233869695926184,
 0.0816496580927726,
 0.0816496580927726,
 0.08134892168199606,
 0.08134892168199606,
 0.08134892168199606,
 0.0809776330178916,
 0.0809776330178916,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08032193289024989,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.08017837257372731,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07905694150420949,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07798128673650545,
 0.07726674092862558,
 0.07726674092862558,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07694837640638656,
 0.07669649888473705,
 0.07669649888473705,
 0.07669649888473705,
 0.07669649888473705,
 0.0761386987626881,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.075955452531275,
 0.07505866250408015,
 0.07500000000000001,
 0.07500000000000001,
 0.07500000000000001,
 0.07500000000000001,
 0.07500000000000001,
 0.074535599249993,
 0.074535599249993,
 0.074535599249993,
 0.074535599249993,
 0.074535599249993,
 0.07407971974871923,
 0.07407971974871923,
 0.07407971974871923,
 0.07407971974871923,
 0.07352146220938077,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07319250547113999,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07254762501100116,
 0.07233642332556181,
 0.07233642332556181,
 0.07233642332556181,
 0.07233642332556181,
 0.07207499701564472,
 0.07150969419341943,
 0.07150969419341943,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07071067811865475,
 0.07042952122737639,
 0.06993786061802354,
 0.06993786061802354,
 0.06993786061802354,
 0.06993786061802354,
 0.06993786061802354,
 0.06918984060216639,
 0.06918984060216639,
 0.06918984060216639,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06900655593423542,
 0.06859943405700353,
 0.06846531968814579,
 0.06846531968814579,
 0.06780635036208103,
 0.06776309271789384,
 0.06776309271789384,
 0.0674199862463242,
 0.0674199862463242,
 0.0674199862463242,
 0.0670820393249937,
 0.0670820393249937,
 0.0670401523153991,
 0.06657795516141343,
 0.06642111641550714,
 0.06642111641550714,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0659380473395787,
 0.0657793514480272,
 0.0657793514480272,
 0.0657793514480272,
 0.0657793514480272,
 0.0651558364144604,
 0.0651558364144604,
 0.0651558364144604,
 0.0651558364144604,
 0.0651558364144604,
 0.06488856845230502,
 0.06488856845230502,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679029,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06454972243679027,
 0.06396021490668313,
 0.06396021490668313,
 0.06396021490668313,
 0.0632455532033676,
 0.0632455532033676,
 0.0632455532033676,
 0.0632455532033676,
 0.0632455532033676,
 0.0632455532033676,
 0.0632455532033676,
 0.06282808624375433,
 0.06282808624375433,
 0.06282808624375433,
 0.06228410989030497,
 0.062017367294604234,
 0.062017367294604234,
 0.062017367294604234,
 0.062017367294604234,
 0.06175402271944638,
 0.06175402271944638,
 0.061754022719446376,
 0.06123724356957945,
 0.06123724356957945,
 0.06123724356957945,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.060858061945018464,
 0.0607332247634187,
 0.0607332247634187,
 0.060241449667687415,
 0.060241449667687415,
 0.05976143046671968,
 0.05976143046671968,
 0.05976143046671968,
 0.05976143046671968,
 0.05976143046671968,
 0.05976143046671968,
 0.05976143046671968,
 0.05976143046671968,
 0.05976143046671968,
 0.05976143046671968,
 0.059761430466719674,
 0.05976143046671967,
 0.05976143046671967,
 0.05976143046671967,
 0.05883484054145521,
 0.058722021951470346,
 0.058722021951470346,
 0.058722021951470346,
 0.058722021951470346,
 0.058722021951470346,
 0.058722021951470346,
 0.058722021951470346,
 0.058722021951470346,
 0.058722021951470346,
 0.05838742081211422,
 0.057735026918962574,
 0.057735026918962574,
 0.057735026918962574,
 0.057735026918962574,
 0.057735026918962574,
 0.057735026918962574,
 0.057735026918962574,
 0.057735026918962574,
 0.057735026918962574,
 0.057735026918962574,
 0.057735026918962574,
 0.057522374163552784,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056796183424706485,
 0.056694670951384085,
 0.055901699437494755,
 0.055901699437494755,
 0.05590169943749474,
 0.05590169943749474,
 0.05590169943749474,
 0.05590169943749474,
 0.05590169943749474,
 0.0555174907648204,
 0.05547001962252292,
 0.055257896399553766,
 0.05514109665703558,
 0.05514109665703558,
 0.05514109665703558,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.055048188256318034,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05423261445466404,
 0.05345224838248488,
 0.05345224838248488,
 0.05345224838248488,
 0.05345224838248488,
 0.05345224838248488,
 0.05345224838248488,
 0.05345224838248488,
 0.05345224838248488,
 0.053367605022361514,
 0.052704627669472995,
 0.052704627669472995,
 0.052704627669472995,
 0.05270462766947299,
 0.05270462766947299,
 0.05270462766947299,
 0.051987524491003634,
 0.051987524491003634,
 0.051987524491003634,
 0.051987524491003634,
 0.051987524491003634,
 0.051987524491003634,
 0.051987524491003634,
 0.051987524491003634,
 0.051987524491003634,
 0.051987524491003634,
 0.051987524491003634,
 0.051298917604257706,
 0.051298917604257706,
 0.051298917604257706,
 0.051298917604257706,
 0.051298917604257706,
 0.051298917604257706,
 0.051298917604257706,
 0.051298917604257706,
 0.051298917604257706,
 0.051298917604257706,
 0.051298917604257706,
 0.05063696835418333,
 0.05063696835418333,
 0.05063696835418333,
 0.05063696835418333,
 0.05063696835418333,
 0.05063696835418333,
 0.05063696835418333,
 0.05063696835418333,
 0.05028011423654932,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.049386479832479485,
 0.049386479832479485,
 0.049386479832479485,
 0.049386479832479485,
 0.049386479832479485,
 0.049386479832479485,
 0.049386479832479485,
 0.049386479832479485,
 0.048795003647426664,
 0.048795003647426664,
 0.048795003647426664,
 0.048795003647426664,
 0.048795003647426664,
 0.048795003647426664,
 0.048795003647426664,
 0.04841229182759271,
 0.04822428221704121,
 0.04822428221704121,
 0.04822428221704121,
 0.04822428221704121,
 0.04822428221704121,
 0.04822428221704121,
 0.04822428221704121,
 0.04767312946227962,
 0.04767312946227962,
 0.04767312946227962,
 0.04767312946227962,
 0.04767312946227962,
 0.04714045207910317,
 0.04714045207910317,
 0.04714045207910317,
 0.04714045207910317,
 0.04714045207910317,
 0.04714045207910317,
 0.04714045207910317,
 0.04714045207910317,
 0.04714045207910317,
 0.04714045207910317,
 0.04673827146373169,
 0.04662524041201569,
 0.04662524041201569,
 0.04662524041201569,
 0.04662524041201569,
 0.04662524041201569,
 0.04662524041201569,
 0.04662524041201569,
 0.04662524041201569,
 0.04662524041201569,
 0.04662524041201569,
 0.04662524041201569,
 0.04662524041201569,
 0.04662524041201569,
 0.04612656040144426,
 0.04612656040144426,
 0.04612656040144426,
 0.04612656040144426,
 0.04612656040144426,
 0.04564354645876385,
 0.04564354645876385,
 0.04564354645876385,
 0.04564354645876385,
 0.04564354645876385,
 0.04564354645876385,
 0.04564354645876385,
 0.04564354645876385,
 0.04564354645876385,
 0.04517539514526256,
 0.04517539514526256,
 0.04517539514526256,
 0.04517539514526256,
 0.04517539514526256,
 0.04517539514526256,
 0.04517539514526256,
 0.04517539514526256,
 0.044721359549995794,
 0.044721359549995794,
 0.04442616583193193,
 0.04428074427700476,
 0.04428074427700476,
 0.04428074427700476,
 0.04428074427700476,
 0.04404151646360276,
 0.043852900965351466,
 0.043852900965351466,
 0.043852900965351466,
 0.043852900965351466,
 0.04343722427630694,
 0.04343722427630694,
 0.04343722427630694,
 0.04343722427630694,
 0.04343722427630694,
 0.04343722427630694,
 0.04303314829119352,
 0.04303314829119352,
 0.04303314829119352,
 0.04264014327112209,
 0.04264014327112209,
 0.04264014327112209,
 0.04264014327112209,
 0.04225771273642583,
 0.04225771273642583,
 0.04225771273642583,
 0.04225771273642583,
 0.04225771273642583,
 0.04225771273642583,
 0.041885390829169554,
 0.041885390829169554,
 0.04152273992686998,
 0.04116934847963092,
 0.0408248290463863,
 0.0408248290463863,
 0.0408248290463863,
 0.0408248290463863,
 0.0408248290463863,
 0.0408248290463863,
 0.0408248290463863,
 0.0408248290463863,
 0.04016096644512494,
 0.03984095364447978,
 0.03984095364447978,
 0.03984095364447978,
 0.03952847075210474,
 0.03952847075210474,
 0.03952847075210474,
 0.03952847075210474,
 0.03952847075210474,
 0.03952847075210474,
 0.03922322702763681,
 0.03922322702763681,
 0.03892494720807615,
 0.03892494720807615,
 0.03892494720807615,
 0.038348249442368525,
 0.038348249442368525,
 0.038348249442368525,
 0.038348249442368525,
 0.038348249442368525,
 0.038348249442368525,
 0.038348249442368525,
 0.03806934938134405,
 0.03806934938134405,
 0.03779644730092272,
 0.03779644730092272,
 0.0372677996249965,
 0.0372677996249965,
 0.0372677996249965,
 0.0372677996249965,
 0.0372677996249965,
 0.0372677996249965,
 0.0372677996249965,
 0.0372677996249965,
 0.0372677996249965,
 0.037011660509880265,
 0.036514837167011066,
 0.03627381250550058,
 0.03627381250550058,
 0.03627381250550058,
 0.03627381250550058,
 0.03627381250550058,
 0.03603749850782236,
 0.03603749850782236,
 0.03603749850782236,
 0.03580574370197164,
 0.03580574370197164,
 0.03557840334824101,
 0.03557840334824101,
 0.035355339059327376,
 0.035355339059327376,
 0.035355339059327376,
 0.035355339059327376,
 0.035355339059327376,
 0.035355339059327376,
 0.035355339059327376,
 0.035355339059327376,
 0.035355339059327376,
 0.03492151478847891,
 0.03471050672503116,
 0.03471050672503116,
 0.03450327796711771,
 0.03450327796711771,
 0.03450327796711771,
 0.03450327796711771,
 0.03450327796711771,
 0.03450327796711771,
 0.03450327796711771,
 0.03450327796711771,
 0.03450327796711771,
 0.03450327796711771,
 0.03450327796711771,
 0.03450327796711771,
 0.03450327796711771,
 0.034299717028501764,
 0.034299717028501764,
 0.03390317518104052,
 0.0337099931231621,
 0.0337099931231621,
 0.0337099931231621,
 0.0337099931231621,
 0.0337099931231621,
 0.0337099931231621,
 0.0337099931231621,
 0.0337099931231621,
 0.0337099931231621,
 0.03352007615769955,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.03296902366978935,
 0.032274861218395144,
 0.032274861218395144,
 0.032274861218395144,
 0.032274861218395144,
 0.032274861218395144,
 0.032274861218395144,
 0.032274861218395144,
 0.032274861218395144,
 0.032274861218395144,
 0.032274861218395144,
 0.032108064953396784,
 0.031943828249996996,
 0.0316227766016838,
 0.0316227766016838,
 0.0316227766016838,
 0.0316227766016838,
 0.0316227766016838,
 0.0316227766016838,
 0.0316227766016838,
 0.0316227766016838,
 0.0316227766016838,
 0.031008683647302117,
 0.031008683647302117,
 0.031008683647302117,
 0.031008683647302117,
 0.031008683647302117,
 0.031008683647302117,
 0.031008683647302117,
 0.031008683647302117,
 0.031008683647302117,
 0.031008683647302117,
 0.031008683647302117,
 0.030429030972509232,
 0.030429030972509232,
 0.030429030972509232,
 0.030429030972509232,
 0.030429030972509232,
 0.030429030972509232,
 0.030429030972509232,
 0.030429030972509232,
 0.030429030972509232,
 0.030429030972509232,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.02988071523335984,
 0.029361010975735173,
 0.029361010975735173,
 0.029361010975735173,
 0.029361010975735173,
 0.029361010975735173,
 0.029361010975735173,
 0.029361010975735173,
 0.029361010975735173,
 0.029361010975735173,
 0.029361010975735173,
 0.029361010975735173,
 0.028867513459481287,
 0.028867513459481287,
 0.028867513459481287,
 0.028867513459481287,
 0.028867513459481287,
 0.028867513459481287,
 0.028867513459481287,
 0.028867513459481287,
 0.028867513459481287,
 0.028867513459481287,

In [140]:
list(enumerate(similarity[0])) # it shows the distance with respected movies from 0th movie now we sort these tuples so that we can get the most similar movies

[(0, 1.0000000000000002),
 (1, 0.08257228238447706),
 (2, 0.055048188256318034),
 (3, 0.03492151478847891),
 (4, 0.1649915822768611),
 (5, 0.10963225241337866),
 (6, 0.018380365552345193),
 (7, 0.15975241260567347),
 (8, 0.05590169943749474),
 (9, 0.07071067811865475),
 (10, 0.10259783520851541),
 (11, 0.07319250547113999),
 (12, 0.08385254915624211),
 (13, 0.04264014327112209),
 (14, 0.10540925533894598),
 (15, 0.04225771273642583),
 (16, 0.07319250547113999),
 (17, 0.13043729868748774),
 (18, 0.10380684981717495),
 (19, 0.0761386987626881),
 (20, 0.053367605022361514),
 (21, 0.08519427513705972),
 (22, 0.055048188256318034),
 (23, 0.09486832980505139),
 (24, 0.051987524491003634),
 (25, 0.05028011423654932),
 (26, 0.15389675281277312),
 (27, 0.1619552660357832),
 (28, 0.11180339887498948),
 (29, 0.0651558364144604),
 (30, 0.0670820393249937),
 (31, 0.15214515486254615),
 (32, 0.08856148855400953),
 (33, 0.09682458365518543),
 (34, 0.0),
 (35, 0.08964214570007953),
 (36, 0.16878498775964426),
 (37, 0.07798128673650545),
 (38, 0.056694670951384085),
 (39, 0.075955452531275),
 (40, 0.051298917604257706),
 (41, 0.1328422328310143),
 (42, 0.0),
 (43, 0.11070186069251191),
 (44, 0.0372677996249965),
 (45, 0.08770580193070293),
 (46, 0.16269784336399212),
 (47, 0.20080483222562476),
 (48, 0.06282808624375433),
 (49, 0.058722021951470346),
 (50, 0.10846522890932808),
 (51, 0.07352146220938077),
 (52, 0.14815943949743846),
 (53, 0.04612656040144426),
 (54, 0.031008683647302117),
 (55, 0.06488856845230502),
 (56, 0.1264911064067352),
 (57, 0.02711630722733202),
 (58, 0.04264014327112209),
 (59, 0.07207499701564472),
 (60, 0.024397501823713332),
 (61, 0.1978141420187361),
 (62, 0.074535599249993),
 (63, 0.07726674092862558),
 (64, 0.028398091712353243),
 (65, 0.01863389981249825),
 (66, 0.022821773229381927),
 (67, 0.1651445647689541),
 (68, 0.12171612389003693),
 (69, 0.04404151646360276),
 (70, 0.075955452531275),
 (71, 0.075955452531275),
 (72, 0.11180339887498948),
 (73, 0.03296902366978935),
 (74, 0.20981358185407062),
 (75, 0.08385254915624211),
 (76, 0.06846531968814579),
 (77, 0.013975424859373685),
 (78, 0.049386479832479485),
 (79, 0.07071067811865475),
 (80, 0.031943828249996996),
 (81, 0.09439751632913289),
 (82, 0.075955452531275),
 (83, 0.20328927815368153),
 (84, 0.13135265938214027),
 (85, 0.095831484749991),
 (86, 0.075955452531275),
 (87, 0.10690449676496976),
 (88, 0.08519427513705972),
 (89, 0.055257896399553766),
 (90, 0.058722021951470346),
 (91, 0.13762047064079508),
 (92, 0.0607332247634187),
 (93, 0.04662524041201569),
 (94, 0.158113883008419),
 (95, 0.11656310103003922),
 (96, 0.08808303292720551),
 (97, 0.07071067811865475),
 (98, 0.07071067811865475),
 (99, 0.023570226039551584),
 (100, 0.06900655593423542),
 (101, 0.08134892168199606),
 (102, 0.10040241611281236),
 (103, 0.07726674092862558),
 (104, 0.055048188256318034),
 (105, 0.09682458365518543),
 (106, 0.0408248290463863),
 (107, 0.0809776330178916),
 (108, 0.15348515337873014),
 (109, 0.06900655593423542),
 (110, 0.02306328020072213),
 (111, 0.12824729401064427),
 (112, 0.08017837257372731),
 (113, 0.04767312946227962),
 (114, 0.04343722427630694),
 (115, 0.048795003647426664),
 (116, 0.04517539514526256),
 (117, 0.0632455532033676),
 (118, 0.016222142113076255),
 (119, 0.043852900965351466),
 (120, 0.0),
 (121, 0.08134892168199606),
 (122, 0.08808303292720551),
 (123, 0.10963225241337866),
 (124, 0.06396021490668313),
 (125, 0.07042952122737639),
 (126, 0.09644856443408242),
 (127, 0.12780193008453875),
 (128, 0.0),
 (129, 0.08304547985373996),
 (130, 0.02672612419124244),
 (131, 0.10397504898200727),
 (132, 0.057522374163552784),
 (133, 0.029361010975735173),
 (134, 0.11952286093343936),
 (135, 0.0),
 (136, 0.023312620206007845),
 (137, 0.032108064953396784),
 (138, 0.07694837640638656),
 (139, 0.09882117688026185),
 (140, 0.04767312946227962),
 (141, 0.09890707100936805),
 (142, 0.07905694150420949),
 (143, 0.06175402271944638),
 (144, 0.05063696835418333),
 (145, 0.020942695414584777),
 (146, 0.015430334996209194),
 (147, 0.056796183424706485),
 (148, 0.09302605094190636),
 (149, 0.16064386578049977),
 (150, 0.16010281506708454),
 (151, 0.1813690625275029),
 (152, 0.056796183424706485),
 (153, 0.07505866250408015),
 (154, 0.030429030972509232),
 (155, 0.0),
 (156, 0.06175402271944638),
 (157, 0.09486832980505139),
 (158, 0.12909944487358058),
 (159, 0.060858061945018464),
 (160, 0.08784104611578832),
 (161, 0.032274861218395144),
 (162, 0.03296902366978935),
 (163, 0.04822428221704121),
 (164, 0.08017837257372731),
 (165, 0.04714045207910317),
 (166, 0.10690449676496976),
 (167, 0.0632455532033676),
 (168, 0.14467284665112365),
 (169, 0.10758287072798381),
 (170, 0.08606629658238704),
 (171, 0.026352313834736494),
 (172, 0.1318760946791574),
 (173, 0.023312620206007845),
 (174, 0.09644856443408242),
 (175, 0.043852900965351466),
 (176, 0.028867513459481287),
 (177, 0.0),
 (178, 0.024693239916239743),
 (179, 0.06900655593423542),
 (180, 0.021320071635561044),
 (181, 0.020942695414584777),
 (182, 0.09428090415820634),
 (183, 0.06859943405700353),
 (184, 0.15203028496707427),
 (185, 0.05345224838248488),
 (186, 0.036514837167011066),
 (187, 0.12996881122750908),
 (188, 0.01863389981249825),
 (189, 0.07669649888473705),
 (190, 0.06780635036208103),
 (191, 0.04564354645876385),
 (192, 0.0),
 (193, 0.07254762501100116),
 (194, 0.0),
 (195, 0.05976143046671968),
 (196, 0.05345224838248488),
 (197, 0.04428074427700476),
 (198, 0.055048188256318034),
 (199, 0.10380684981717495),
 (200, 0.06454972243679029),
 (201, 0.0),
 (202, 0.028398091712353243),
 (203, 0.07798128673650545),
 (204, 0.022360679774997897),
 (205, 0.074535599249993),
 (206, 0.09890707100936805),
 (207, 0.10259783520851541),
 (208, 0.1533929977694741),
 (209, 0.03296902366978935),
 (210, 0.05),
 (211, 0.019611613513818404),
 (212, 0.0670820393249937),
 (213, 0.05883484054145521),
 (214, 0.02672612419124244),
 (215, 0.06918984060216639),
 (216, 0.05590169943749474),
 (217, 0.04264014327112209),
 (218, 0.03952847075210474),
 (219, 0.060858061945018464),
 (220, 0.17616606585441105),
 (221, 0.021926450482675733),
 (222, 0.08304547985373996),
 (223, 0.07694837640638656),
 (224, 0.052704627669472995),
 (225, 0.048795003647426664),
 (226, 0.028398091712353243),
 (227, 0.08134892168199606),
 (228, 0.11531640100361064),
 (229, 0.07071067811865475),
 (230, 0.07669649888473705),
 (231, 0.0),
 (232, 0.11009637651263607),
 (233, 0.09486832980505139),
 (234, 0.06282808624375433),
 (235, 0.05423261445466404),
 (236, 0.09128709291752769),
 (237, 0.051987524491003634),
 (238, 0.11028219331407116),
 (239, 0.10040241611281236),
 (240, 0.04428074427700476),
 (241, 0.07798128673650545),
 (242, 0.08385254915624211),
 (243, 0.08770580193070293),
 (244, 0.057735026918962574),
 (245, 0.08385254915624211),
 (246, 0.060241449667687415),
 (247, 0.0),
 (248, 0.04343722427630694),
 (249, 0.12909944487358058),
 (250, 0.0),
 (251, 0.03952847075210474),
 (252, 0.02171861213815347),
 (253, 0.059761430466719674),
 (254, 0.06776309271789384),
 (255, 0.0),
 (256, 0.07071067811865475),
 (257, 0.08017837257372731),
 (258, 0.016395645894598822),
 (259, 0.058722021951470346),
 (260, 0.22360679774997896),
 (261, 0.023312620206007845),
 (262, 0.06454972243679027),
 (263, 0.09486832980505139),
 (264, 0.0),
 (265, 0.02795084971874737),
 (266, 0.10397504898200727),
 (267, 0.0674199862463242),
 (268, 0.025),
 (269, 0.030429030972509232),
 (270, 0.09534625892455924),
 (271, 0.07500000000000001),
 (272, 0.029361010975735173),
 (273, 0.02214037213850238),
 (274, 0.06657795516141343),
 (275, 0.11744404390294069),
 (276, 0.057735026918962574),
 (277, 0.05976143046671967),
 (278, 0.11531640100361064),
 (279, 0.11410886614690963),
 (280, 0.0),
 (281, 0.07071067811865475),
 (282, 0.056796183424706485),
 (283, 0.0),
 (284, 0.019174124721184262),
 (285, 0.021926450482675733),
 (286, 0.02041241452319315),
 (287, 0.025318484177091666),
 (288, 0.0),
 (289, 0.035355339059327376),
 (290, 0.060858061945018464),
 (291, 0.04822428221704121),
 (292, 0.09128709291752769),
 (293, 0.02988071523335984),
 (294, 0.11009637651263607),
 (295, 0.10397504898200727),
 (296, 0.03806934938134405),
 (297, 0.04303314829119352),
 (298, 0.0),
 (299, 0.037011660509880265),
 (300, 0.15652475842498528),
 (301, 0.17256712249065836),
 (302, 0.058722021951470346),
 (303, 0.025649458802128853),
 (304, 0.06488856845230502),
 (305, 0.17787811838447135),
 (306, 0.08017837257372731),
 (307, 0.08808303292720551),
 (308, 0.06454972243679029),
 (309, 0.05976143046671968),
 (310, 0.034299717028501764),
 (311, 0.14301938838683886),
 (312, 0.10397504898200727),
 (313, 0.07071067811865475),
 (314, 0.0),
 (315, 0.07233642332556181),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.0674199862463242),
 (320, 0.02988071523335984),
 (321, 0.0),
 (322, 0.2),
 (323, 0.032274861218395144),
 (324, 0.023570226039551584),
 (325, 0.08964214570007953),
 (326, 0.057735026918962574),
 (327, 0.027524094128159017),
 (328, 0.0),
 (329, 0.07500000000000001),
 (330, 0.09877295966495897),
 (331, 0.04517539514526256),
 (332, 0.12824729401064427),
 (333, 0.028398091712353243),
 (334, 0.09877295966495897),
 (335, 0.05),
 (336, 0.0632455532033676),
 (337, 0.02258769757263128),
 (338, 0.0),
 (339, 0.05423261445466404),
 (340, 0.048795003647426664),
 (341, 0.051298917604257706),
 (342, 0.12452441171884351),
 (343, 0.020942695414584777),
 (344, 0.029361010975735173),
 (345, 0.02171861213815347),
 (346, 0.0),
 (347, 0.0),
 (348, 0.05423261445466404),
 (349, 0.08660254037844387),
 (350, 0.051987524491003634),
 (351, 0.0),
 (352, 0.02795084971874737),
 (353, 0.020942695414584777),
 (354, 0.0),
 (355, 0.0372677996249965),
 (356, 0.08519427513705972),
 (357, 0.0),
 (358, 0.05976143046671968),
 (359, 0.058722021951470346),
 (360, 0.0),
 (361, 0.05345224838248488),
 (362, 0.08964214570007953),
 (363, 0.08233869695926184),
 (364, 0.020942695414584777),
 (365, 0.075955452531275),
 (366, 0.051298917604257706),
 (367, 0.0),
 (368, 0.11952286093343936),
 (369, 0.07694837640638656),
 (370, 0.05270462766947299),
 (371, 0.09428090415820634),
 (372, 0.049386479832479485),
 (373, 0.16484511834894675),
 (374, 0.03580574370197164),
 (375, 0.04016096644512494),
 (376, 0.04264014327112209),
 (377, 0.0),
 (378, 0.0),
 (379, 0.04841229182759271),
 (380, 0.02672612419124244),
 (381, 0.08451542547285167),
 (382, 0.0),
 (383, 0.04714045207910317),
 (384, 0.030429030972509232),
 (385, 0.0),
 (386, 0.02171861213815347),
 (387, 0.025),
 (388, 0.0),
 (389, 0.08964214570007951),
 (390, 0.025993762245501817),
 (391, 0.052704627669472995),
 (392, 0.028398091712353243),
 (393, 0.0),
 (394, 0.025318484177091666),
 (395, 0.05423261445466404),
 (396, 0.02214037213850238),
 (397, 0.051298917604257706),
 (398, 0.0),
 (399, 0.024397501823713332),
 (400, 0.09486832980505139),
 (401, 0.02988071523335984),
 (402, 0.04822428221704121),
 (403, 0.10206207261596574),
 (404, 0.058722021951470346),
 (405, 0.02988071523335984),
 (406, 0.01992047682223989),
 (407, 0.021128856368212916),
 (408, 0.03296902366978935),
 (409, 0.0),
 (410, 0.09035079029052512),
 (411, 0.05423261445466404),
 (412, 0.09428090415820634),
 (413, 0.12346619958119871),
 (414, 0.02988071523335984),
 (415, 0.0670401523153991),
 (416, 0.051298917604257706),
 (417, 0.038348249442368525),
 (418, 0.032274861218395144),
 (419, 0.07071067811865475),
 (420, 0.11531640100361064),
 (421, 0.0),
 (422, 0.13801311186847084),
 (423, 0.04767312946227962),
 (424, 0.03779644730092272),
 (425, 0.0651558364144604),
 (426, 0.055901699437494755),
 (427, 0.025),
 (428, 0.052704627669472995),
 (429, 0.0),
 (430, 0.04662524041201569),
 (431, 0.02383656473113981),
 (432, 0.11070186069251191),
 (433, 0.02988071523335984),
 (434, 0.0),
 (435, 0.0337099931231621),
 (436, 0.0),
 (437, 0.02711630722733202),
 (438, 0.025993762245501817),
 (439, 0.029361010975735173),
 (440, 0.026352313834736494),
 (441, 0.028398091712353243),
 (442, 0.04517539514526256),
 (443, 0.05423261445466404),
 (444, 0.0),
 (445, 0.025318484177091666),
 (446, 0.024397501823713332),
 (447, 0.02214037213850238),
 (448, 0.02383656473113981),
 (449, 0.05423261445466404),
 (450, 0.02383656473113981),
 (451, 0.024693239916239743),
 (452, 0.02988071523335984),
 (453, 0.025),
 (454, 0.11918282365569904),
 (455, 0.02306328020072213),
 (456, 0.06396021490668313),
 (457, 0.07905694150420949),
 (458, 0.03603749850782236),
 (459, 0.0316227766016838),
 (460, 0.025649458802128853),
 (461, 0.16854996561581048),
 (462, 0.0),
 (463, 0.031008683647302117),
 (464, 0.0),
 (465, 0.0),
 (466, 0.19364916731037088),
 (467, 0.08528028654224418),
 (468, 0.02795084971874737),
 (469, 0.0657793514480272),
 (470, 0.04517539514526256),
 (471, 0.07500000000000001),
 (472, 0.08257228238447706),
 (473, 0.09428090415820634),
 (474, 0.0),
 (475, 0.06228410989030497),
 (476, 0.09682458365518543),
 (477, 0.0),
 (478, 0.03806934938134405),
 (479, 0.08894600837060251),
 (480, 0.05),
 (481, 0.0),
 (482, 0.028398091712353243),
 (483, 0.11744404390294069),
 (484, 0.0316227766016838),
 (485, 0.051298917604257706),
 (486, 0.055901699437494755),
 (487, 0.1318760946791574),
 (488, 0.07071067811865475),
 (489, 0.0),
 (490, 0.13801311186847084),
 (491, 0.07254762501100116),
 (492, 0.057735026918962574),
 (493, 0.01863389981249825),
 (494, 0.0),
 (495, 0.19364916731037088),
 (496, 0.0),
 (497, 0.0),
 (498, 0.06454972243679029),
 (499, 0.0),
 (500, 0.02672612419124244),
 (501, 0.0816496580927726),
 (502, 0.14301938838683886),
 (503, 0.07694837640638656),
 (504, 0.0),
 (505, 0.1318760946791574),
 (506, 0.0337099931231621),
 (507, 0.2345207879911715),
 (508, 0.1),
 (509, 0.02214037213850238),
 (510, 0.09759000729485333),
 (511, 0.08808303292720551),
 (512, 0.056796183424706485),
 (513, 0.10846522890932808),
 (514, 0.04714045207910317),
 (515, 0.025649458802128853),
 (516, 0.024112141108520606),
 (517, 0.0),
 (518, 0.05),
 (519, 0.0),
 (520, 0.0),
 (521, 0.023570226039551584),
 (522, 0.0),
 (523, 0.04767312946227962),
 (524, 0.0),
 (525, 0.024112141108520606),
 (526, 0.0),
 (527, 0.0),
 (528, 0.022360679774997897),
 (529, 0.11410886614690963),
 (530, 0.09302605094190636),
 (531, 0.04517539514526256),
 (532, 0.019611613513818404),
 (533, 0.0632455532033676),
 (534, 0.0816496580927726),
 (535, 0.10540925533894598),
 (536, 0.07071067811865475),
 (537, 0.0659380473395787),
 (538, 0.0),
 (539, 0.24404676504598818),
 (540, 0.05423261445466404),
 (541, 0.08304547985373996),
 (542, 0.03471050672503116),
 (543, 0.07319250547113999),
 (544, 0.05345224838248488),
 (545, 0.027524094128159017),
 (546, 0.062017367294604234),
 (547, 0.08519427513705972),
 (548, 0.0),
 (549, 0.11785113019775792),
 (550, 0.025993762245501817),
 (551, 0.04152273992686998),
 (552, 0.0),
 (553, 0.030429030972509232),
 (554, 0.0),
 (555, 0.04442616583193193),
 (556, 0.025993762245501817),
 (557, 0.12346619958119871),
 (558, 0.0),
 (559, 0.030429030972509232),
 (560, 0.03580574370197164),
 (561, 0.03450327796711771),
 (562, 0.0),
 (563, 0.024693239916239743),
 (564, 0.09486832980505139),
 (565, 0.03892494720807615),
 (566, 0.021128856368212916),
 (567, 0.024693239916239743),
 (568, 0.13762047064079508),
 (569, 0.02171861213815347),
 (570, 0.06900655593423542),
 (571, 0.021128856368212916),
 (572, 0.08032193289024989),
 (573, 0.02076136996343499),
 (574, 0.02258769757263128),
 (575, 0.051987524491003634),
 (576, 0.02711630722733202),
 (577, 0.1336306209562122),
 (578, 0.05976143046671967),
 (579, 0.11359236684941297),
 (580, 0.02214037213850238),
 (581, 0.14680505487867587),
 (582, 0.22140372138502384),
 (583, 0.05),
 (584, 0.0408248290463863),
 (585, 0.0),
 (586, 0.04303314829119352),
 (587, 0.09644856443408242),
 (588, 0.025649458802128853),
 (589, 0.08032193289024989),
 (590, 0.032274861218395144),
 (591, 0.07407971974871923),
 (592, 0.02383656473113981),
 (593, 0.0),
 (594, 0.05063696835418333),
 (595, 0.12056070554260304),
 (596, 0.08528028654224418),
 (597, 0.05),
 (598, 0.038348249442368525),
 (599, 0.029361010975735173),
 (600, 0.06642111641550714),
 (601, 0.03471050672503116),
 (602, 0.041885390829169554),
 (603, 0.05270462766947299),
 (604, 0.06454972243679029),
 (605, 0.0),
 (606, 0.0),
 (607, 0.0607332247634187),
 (608, 0.0),
 (609, 0.04428074427700476),
 (610, 0.05514109665703558),
 (611, 0.02214037213850238),
 (612, 0.0651558364144604),
 (613, 0.03450327796711771),
 (614, 0.055048188256318034),
 (615, 0.031008683647302117),
 (616, 0.0),
 (617, 0.051987524491003634),
 (618, 0.09035079029052512),
 (619, 0.0),
 (620, 0.0),
 (621, 0.06900655593423542),
 (622, 0.019316685232156395),
 (623, 0.0),
 (624, 0.10882143751650175),
 (625, 0.031008683647302117),
 (626, 0.08017837257372731),
 (627, 0.11504474832710557),
 (628, 0.0),
 (629, 0.04714045207910317),
 (630, 0.023312620206007845),
 (631, 0.0202444082544729),
 (632, 0.07694837640638656),
 (633, 0.02306328020072213),
 (634, 0.10259783520851541),
 (635, 0.06993786061802354),
 (636, 0.02672612419124244),
 (637, 0.049386479832479485),
 (638, 0.03296902366978935),
 (639, 0.0),
 (640, 0.04822428221704121),
 (641, 0.0),
 (642, 0.0),
 (643, 0.09325048082403138),
 (644, 0.05345224838248488),
 (645, 0.044721359549995794),
 (646, 0.048795003647426664),
 (647, 0.04714045207910317),
 (648, 0.031008683647302117),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.01801874925391118),
 (653, 0.10606601717798213),
 (654, 0.08233869695926184),
 (655, 0.024112141108520606),
 (656, 0.0),
 (657, 0.03296902366978935),
 (658, 0.048795003647426664),
 (659, 0.024693239916239743),
 (660, 0.09302605094190636),
 (661, 0.1619552660357832),
 (662, 0.0),
 (663, 0.0),
 (664, 0.057735026918962574),
 (665, 0.07233642332556181),
 (666, 0.05),
 (667, 0.0),
 (668, 0.0674199862463242),
 (669, 0.0337099931231621),
 (670, 0.016308201826336053),
 (671, 0.05),
 (672, 0.051987524491003634),
 (673, 0.02151657414559676),
 (674, 0.06993786061802354),
 (675, 0.04662524041201569),
 (676, 0.026352313834736494),
 (677, 0.02383656473113981),
 (678, 0.058722021951470346),
 (679, 0.0),
 (680, 0.07407971974871923),
 (681, 0.028867513459481287),
 (682, 0.02214037213850238),
 (683, 0.04714045207910317),
 (684, 0.0),
 (685, 0.03450327796711771),
 (686, 0.0),
 (687, 0.10127393670836667),
 (688, 0.04662524041201569),
 (689, 0.0),
 (690, 0.025649458802128853),
 (691, 0.09302605094190634),
 (692, 0.1129384878631564),
 (693, 0.0),
 (694, 0.021128856368212916),
 (695, 0.05976143046671968),
 (696, 0.0),
 (697, 0.0),
 (698, 0.021320071635561044),
 (699, 0.0),
 (700, 0.028398091712353243),
 (701, 0.05423261445466404),
 (702, 0.02214037213850238),
 (703, 0.019034674690672024),
 (704, 0.07150969419341943),
 (705, 0.024397501823713332),
 (706, 0.024693239916239743),
 (707, 0.0),
 (708, 0.02383656473113981),
 (709, 0.0),
 (710, 0.04303314829119352),
 (711, 0.05976143046671968),
 (712, 0.0),
 (713, 0.02672612419124244),
 (714, 0.0),
 (715, 0.09486832980505139),
 (716, 0.03296902366978935),
 (717, 0.0),
 (718, 0.0408248290463863),
 (719, 0.0),
 (720, 0.024693239916239743),
 (721, 0.02988071523335984),
 (722, 0.0),
 (723, 0.025318484177091666),
 (724, 0.023570226039551584),
 (725, 0.0),
 (726, 0.0),
 (727, 0.03390317518104052),
 (728, 0.06918984060216639),
 (729, 0.0),
 (730, 0.015285446012893575),
 (731, 0.05063696835418333),
 (732, 0.07407971974871923),
 (733, 0.03952847075210474),
 (734, 0.04564354645876385),
 (735, 0.04662524041201569),
 (736, 0.0316227766016838),
 (737, 0.07500000000000001),
 (738, 0.0),
 (739, 0.035355339059327376),
 (740, 0.11656310103003922),
 (741, 0.05345224838248488),
 (742, 0.02988071523335984),
 (743, 0.025),
 (744, 0.05345224838248488),
 (745, 0.0632455532033676),
 (746, 0.08017837257372731),
 (747, 0.02258769757263128),
 (748, 0.0337099931231621),
 (749, 0.0),
 (750, 0.04612656040144426),
 (751, 0.0337099931231621),
 (752, 0.06993786061802354),
 (753, 0.02795084971874737),
 (754, 0.12659242088545833),
 (755, 0.05514109665703558),
 (756, 0.028867513459481287),
 (757, 0.025649458802128853),
 (758, 0.024397501823713332),

In [141]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6] #now here we have sorted it on the basis of distance as x[1] denotes distance here and finding best 5 movies similar to that

[(539, 0.24404676504598818),
 (1192, 0.23596995186213465),
 (507, 0.2345207879911715),
 (1214, 0.2271099895830676),
 (1202, 0.22499999999999998)]

In [142]:
new_df.iloc[1216].title # printing the name of the movie through its index

'Autumn in New York'

In [143]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)# printing the index of the most recommended 5 movies
        print()

In [144]:
recommend('Red Planet')

The Martian

Mission to Mars

Sunshine

Children of Men

Total Recall